### ISSUE TITLE
[doc] consider clarifying the relationship to rpav/c2ffi

### ISSUE THREAD

**Issue by attila-lendvai** [bottlenoselabs/c2ffi#34]
here are some questions that i had after reading the readme:

- why another project on the same name? doesn't seem to be a fork of it.
- what are the planned features that [the other c2ffi](https://github.com/rpav/c2ffi) doesn't support?

**Comment by lithiumtoast** [comment]
Hey @attila-lendvai,

I had it named as something different but then re-wrote it with tests under the name `c2ffi` as that accurately describes the project. If you have a better name I am open to suggestions.

- This project only supports C. The other one apparently supports C++, ObjC, etc. I wrote in the `README` why only C is supported.
- This project fully supports macros objects by parsing via C++ using `auto`.
- This project is intended to be used to generate the `.JSON` output for each target platform (clang target triple). Then merged together into guaranteed cross platform `.JSON` output. If it can't, then there is likely something wrong with the C code.
- The `README` contains a brain dump of things which one should do and do not in C for interoperability.
- This project is used directly by another project [c2cs](https://github.com/bottlenoselabs/c2cs) to generate C# bindings.

Cheers

**Comment by attila-lendvai** [comment]
thanks for the detailed answer @lithiumtoast !

consider adding some of this to the readme for the possible other wondering hackers... :)

happy hacking!

**Comment by lithiumtoast** [comment]
Thanks @attila-lendvai,

I updated the README with some information.
